name: univ_approx_th

channels: 
    - defaults
    - conda-forge
    - plotly
dependencies:
    - numpy
    - matplotlib
    - python>=3.7
    - jupyterlab
    - dash
    - plotly
    - jupyter-dash
